version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:12.9.1
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

        #TODO: Implement tests
      #- run:
         # name: test
          #command: npm test
      #- run:
          #name: code-coverage
          #command: './node_modules/.bin/nyc report --reporter=text-lcov'
      #- store_artifacts:
          #path: test-results.xml
          #prefix: tests
      #- store_artifacts:
          #path: coverage
          #prefix: coverage
      #- store_test_results:
          #path: test-results.xml
  deploy:
    - image: buildpack-deps:mars/create-react-app
    steps:
      - checkout
      - run:
          name: Deploy CircleCI-Integration to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git CircleCI-Integration
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: CircleCI-Integration
